"use client"
import { useState, useEffect } from "react"
import { createClient } from "@supabase/supabase-js"
const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!)
export default function AdminPage(){
  const [email,setEmail]=useState("admin@alsafatraders.pk")
  const [pass,setPass]=useState("")
  const [logged,setLogged]=useState(false)
  const [products,setProducts]=useState<any[]>([])
  const [title,setTitle]=useState("")
  const [price,setPrice]=useState("")
  const [daraz,setDaraz]=useState("")
  const login=async()=>{ const {error}=await supabase.auth.signInWithPassword({email,password:pass}); if(!error){ setLogged(true); load() } else alert(error.message) }
  const load=async()=>{ const {data}=await supabase.from("products").select("*").order("id",{ascending:false}); if(data) setProducts(data) }
  useEffect(()=>{ supabase.auth.getSession().then(({data})=>{ if(data.session){ setLogged(true); load() } }) },[])
  const addProduct=async()=>{ if(!title||!price||!daraz) return alert("Sab fill karo"); const {error}=await supabase.from("products").insert([{title,price,daraz_url:daraz}]); if(!error){ setTitle("");setPrice("");setDaraz(""); load(); alert("✅ Added!") } }
  const delProduct=async(id:number)=>{ await supabase.from("products").delete().eq("id",id); load() }
  if(!logged) return (<div style={{minHeight:"100vh",background:"#000",display:"flex",alignItems:"center",justifyContent:"center"}}><div style={{background:"#111",border:"1px solid #D4AF37",padding:40,borderRadius:16,width:350}}><h1 style={{color:"#D4AF37",fontSize:28,fontWeight:800,textAlign:"center"}}>AL SAFA ADMIN</h1><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email" style={{width:"100%",marginTop:20,padding:12,background:"#000",border:"1px solid #333",color:"#fff",borderRadius:8}}/><input type="password" value={pass} onChange={e=>setPass(e.target.value)} placeholder="Password" style={{width:"100%",marginTop:12,padding:12,background:"#000",border:"1px solid #333",color:"#fff",borderRadius:8}}/><button onClick={login} style={{width:"100%",marginTop:20,padding:12,background:"#D4AF37",color:"#000",fontWeight:700,borderRadius:8}}>LOGIN</button></div></div>)
  return (<div style={{minHeight:"100vh",background:"#000",color:"#fff",padding:20}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",borderBottom:"1px solid #D4AF37",paddingBottom:15}}><h1 style={{color:"#D4AF37",fontSize:24,fontWeight:800}}>AL SAFA - DASHBOARD</h1><button onClick={()=>{supabase.auth.signOut(); setLogged(false)}} style={{background:"#222",color:"#fff",padding:"8px 16px",borderRadius:8,border:"1px solid #333"}}>Logout</button></div><div style={{background:"#111",border:"1px solid #222",padding:20,borderRadius:12,marginTop:20}}><h2 style={{color:"#D4AF37",marginBottom:15}}>Add New Product</h2><div style={{display:"grid",gap:12}}><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Title" style={{padding:12,background:"#000",border:"1px solid #333",color:"#fff",borderRadius:8}}/><input value={price} onChange={e=>setPrice(e.target.value)} placeholder="Price" style={{padding:12,background:"#000",border:"1px solid #333",color:"#fff",borderRadius:8}}/><input value={daraz} onChange={e=>setDaraz(e.target.value)} placeholder="Daraz Link" style={{padding:12,background:"#000",border:"1px solid #333",color:"#fff",borderRadius:8}}/></div><button onClick={addProduct} style={{marginTop:15,padding:"12px 30px",background:"#D4AF37",color:"#000",fontWeight:800,borderRadius:8}}>ADD PRODUCT +</button></div><div style={{marginTop:30}}>{products.map((p:any)=>(<div key={p.id} style={{background:"#111",border:"1px solid #222",padding:15,borderRadius:10,display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:10}}><div><b style={{color:"#D4AF37"}}>{p.title}</b> - Rs {p.price}</div><button onClick={()=>delProduct(p.id)} style={{background:"red",color:"#fff",padding:"6px 12px",borderRadius:6}}>Delete</button></div>))}</div></div>)
}
